name: ⏯️ Generate pre-release PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    uses: newrelic/newrelic-agent-control/.github/workflows/shared_create_prerelease_pr.yml@28fabfe393721f1faf435cdbe05ef6f9c9972784 # main
    with:
      cargo_toml_path: "opamp-client/Cargo.toml"
    secrets:
      app_id: ${{ secrets.AGENT_CONTROL_APP_ID }}
      app_private_key: ${{ secrets.AGENT_CONTROL_APP_PKEY }}
