name: release
on:
  release:
    types:
      - prereleased
      - released
  push:
    tags:
      - '*'
permissions:
  contents: read
jobs:
  third-party-notices-check:
    name: Check third party licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: newrelic/rust-licenses-noticer@9d9bb4a5137f7c9d528b4ada1f505866947feccf # v1
        with:
          template-file: THIRD_PARTY_NOTICES.md.tmpl

  build:
    needs: [ third-party-notices-check ]
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Verify version matches tag
        run: |
          VERSION_IN_CARGO=$(sed -n 's/^version = "\(.*\)"/\1/p' opamp-client/Cargo.toml)
          if [ "${VERSION_IN_CARGO}" != "${{ github.ref_name }}" ]; then
            echo "Package version specified in Cargo.toml (${VERSION_IN_CARGO}) differs from tag (${{ github.ref_name }}), exiting"
            exit 1
          fi

      - name: Send notification to Slack Workflow
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          payload: |
            {
              "text": ":x: Hi AC, an OpAMP client release has just failed"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
